# Generated by cucumber-sinatra. (2013-11-10 10:32:49 +0000)

ENV['RACK_ENV'] = 'test'

require './server'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/chitter.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

require 'database_cleaner'
require 'database_cleaner/cucumber'

Capybara.app = Chitter
DatabaseCleaner.strategy = :truncation

class ChitterWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

Before do
    DatabaseCleaner.start
  end

After do 
  DatabaseCleaner.clean
end

World do
  ChitterWorld.new
end
